name: Sync to Mirror Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Push to mirror repo
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          echo "TOKEN=${#TOKEN}"
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          git remote add mirror https://$TOKEN@github.com/Lindist/Lindist.github.io.git
          git push mirror HEAD:main --force
