name: Sync to Mirror Repo
on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push to mirror
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name  "GitHub Action"

          git remote add mirror https://x-access-token:${TOKEN}@github.com/Lindist/Lindist.github.io.git
          git push mirror HEAD:main --force